### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by kachick**
Is this correct?

### CODE REVIEW

**Comment by smtlaissezfaire** [comment]
If no tests fail either way, I wonder if it's no-op code

**Comment by cheald** [comment]
This is incorrect - the `target` accessor is used rather than the `@target` ivar to allow for overrides by plugins or whatnot.

**Comment by smtlaissezfaire** [comment]
Yeah but then shouldn't it be "self."  Otherwise this just sets a local, right?

**Comment by cheald** [comment]
Ah, hm, right. There isn't a setter - it's set up via attr_reader, not attr_accessor. We should cover this with a test, and then test the fix.

**Comment by kachick** [comment]
I guess you changed the codebase, so this PR is conflicted, but looks still having similar issue 😄 

https://github.com/mongomapper/mongomapper/blob/3123afb71699a6d56932fcf213350854b06f3ea6/lib/mongo_mapper/plugins/associations/proxy/collection.rb#L41

But I can't add tests. So I 🙏 someone take over this issue.
I'll close this PR 👋

**Pull request closed without merging**
