### PR TITLE
Consider polymorphic belongs_to in counter_cache

### PR DESCRIPTION
**Pull request by bhernez**
When there's a polymorphic belongs_to, counter_cache fails to work because it doesn't exists a class named as the polymorphic association. On polymorphic associations is not possible to know previously if the parent model has the correct attribute to increment, so we need to check in the callback if the parent model responds to the method.

### CODE REVIEW

**Comment by smtlaissezfaire** [comment]
Hmm - good idea @bhernez.  Do you think it should raise if it's missing the key (to match the behavior for non-polymorphic associations).  Should it create set the value as '0' instead?  I don't like the idea of it failing silently.

**Comment by smtlaissezfaire** [comment]
WDYT of this: https://gist.github.com/smtlaissezfaire/be1321443ebb32ff00d9

It adds specs as well (which is missing from your patch).

@cheald I'd be curious about your input, as well.

**Comment by smtlaissezfaire** [comment]
I'm going to merge my patch (a variation on @bhernez  with some tests + error checking).  Thanks!

**Comment by bhernez** [comment]
@smtlaissezfaire I didn't consider raising  an error (and let it fail silently) because I personally don't like when a simple after_save callback, as a counter, fails and then it rollbacks the action; but Mongo works different than ActiveRecord and most of the people are confort with that way, so I totally support your modifications. Thanks for making a better commit!

**Pull request closed without merging**
