### PR TITLE
Support Rails 7.1

### PR DESCRIPTION
**Pull request by a2ikm**
Rails 7.1 Release Note
https://guides.rubyonrails.org/7_1_release_notes.html

### CODE REVIEW

**Comment by smtlaissezfaire** [comment]
👍

**Comment by a2ikm** [comment]
@smtlaissezfaire 
Thank you for your super rapid review!

I added [a commit](https://github.com/mongomapper/mongomapper/pull/720/commits/6c06e523cb63b74e4865e020b31895fc9e9c3195) to fix a deprecation warning for `Module.deprecate` used at `MongoMapper::Plugins::StrongParameters`.
```
DEPRECATION WARNING: Module.deprecate without a deprecator is deprecated (called from singleton class at /home/runner/work/mongomapper/mongomapper/lib/mongo_mapper/plugins/strong_parameters.rb:9)
```
(cited from [this log](https://github.com/mongomapper/mongomapper/actions/runs/6448557610/job/17505951546?pr=720#step:6:9))

This commit introduces a new deprecation warning for calling `attr_accessible` and `attr_protected` like the following: 
```
DEPRECATION WARNING: attr_protected is deprecated and will be removed from mongo_mapper 1.0
```

Do you have any concerns?
It sounds reasonable to me to deprecate these methods like ActiveRecord, but actually we don't have any plan to remove them.

Alternatively, we can solve the warning by making `MongoMapper::Plugins::Accessible` and `MongoMapper::Plugins::Protected` optional. It is because `attr_accessible` and `attr_protected` are defined by these plugins which are enabled by default.
This change requires developers to add some `include`s, but it wouldn't be so hard.

How do you think?

**Comment by smtlaissezfaire** [comment]
No concerns, sounds good to me!

**Comment by a2ikm** [comment]
@smtlaissezfaire 
Please release a new version 🙏

**Comment by smtlaissezfaire** [comment]
@a2ikm https://rubygems.org/gems/mongo_mapper/versions/0.16.0

**Comment by a2ikm** [comment]
Thank you!! 🙌

**Pull request merged**
