### PR TITLE
Inverse of many-to-many association

### PR DESCRIPTION
**Pull request by hubertlepicki**
Hi guys,

I just made inverse of many-to-many association support into MongoMapper. Essentially, it's using (and depends on having defined) normal "many :in => xxx" association. You use it with the following API:

class Book
  key :author_ids, Array
  many :authors, :in => :author_ids
end

class Author
  many :books, :in_foreign => {:author_ids}, :as => :author
end

Please let me know if that's any good. I was thinking there is a possibility to have some base class for InArrayProxy and InForeignArrayProxy, as well as test cases, but would be good if you could let me know if you want to keep those separate or I should do it.

### CODE REVIEW

**Comment by smtlaissezfaire** [comment]
I'm merging this and going to use "from" for now.   

We can always rename / change keys later.  Perfect is definitely the enemy of done.

**Comment by smtlaissezfaire** [comment]
Also I suspect that the best syntax to use here is `:foreign_key => :model_ids, :as => "Model"`.  

One implementation detail: instead of having a bunch of different proxy classes, why not just have one base`ManyDocumentsProxy` class + extend with a variety of modules (a `ManyEmbeddedPolymorphicProxy` module, etc)?

**Comment by smtlaissezfaire** [comment]
Merged in 8030d11024c3316e11e9f0d18457911618aafa5e

**Comment by leifcr** [comment]
@smtlaissezfaire Awesome. Thanks for fixing.

**Pull request closed without merging**
