### PR TITLE
Specify Rails' minor version in CI

### PR DESCRIPTION
**Pull request by a2ikm**
This PR updates gemfiles to install rails whose version matches with their filenames.
For example, gemfiles/rails5_0.gemfile should install rails 5.0, but it installs rails 5.2 now.

### CODE REVIEW

**Comment by a2ikm** [comment]
Testing with Ruby 2.7.2 and gemfiles/rails5_0.gemfile failed. Its errors are for dirty.

I mixed this PR and https://github.com/mongomapper/mongomapper/pull/667 at https://github.com/a2ikm/mongomapper/pull/5, and all tests passed.
So please check https://github.com/mongomapper/mongomapper/pull/667 before reviewing this PR 🙏

**Comment by smtlaissezfaire** [comment]
Why do we want minor versions to be checked?

**Comment by a2ikm** [comment]
Thank you for your reply!

It is because Rails can make internal breaking changes in minor versions.
For example, ActiveModel and ActiveRecord changed their structures and moved a commonly used instance variable `@attributes` in 5.2 with https://github.com/rails/rails/pull/30985.

Even if it won't happen, checking minor versions would help us guarantee compatibilities between most Rails versions, I think.

**Comment by smtlaissezfaire** [comment]
Hi @a2ikm! Thanks for your many contributions.

Wouldn't we want to check against most recent rails versions, not x.x.0 versions, though?

**Comment by a2ikm** [comment]
@smtlaissezfaire 
Yes, we want to do that. We can do that with '~> x.x.0', I think.
We don't add Gemfile.lock to the repository, then`~> x.x.0` installs most recent versions at runtime within `>= x.x.0` and `< x.(x+1)`.
https://thoughtbot.com/blog/rubys-pessimistic-operator

Of course, it is explicit to specify with the teeny version like 'x.x.x'.
If you prefer it to `~> x.x.0`, I'll update the PR 👍

**Comment by a2ikm** [comment]
Thank you for merging https://github.com/mongomapper/mongomapper/pull/667!
I rebased this branch on the latest master branch.

**Comment by mtsmfm** [comment]
@smtlaissezfaire I think this PR should be merged because currently CI doesn't work against rails 5.0.

**Comment by a2ikm** [comment]
@smtlaissezfaire 
Hi 👋 

Is there any problem or worry with this PR?
I think it just helps us keep compatibilities in all of Rails 5.0, 5.1, 5.2, 6.0, and 6.1.
If you have any blocker, please let me know it 🙏

**Comment by a2ikm** [comment]
The changes in this PR are included in https://github.com/mongomapper/mongomapper/pull/680.

**Comment by smtlaissezfaire** [comment]
Closing this in favor of https://github.com/mongomapper/mongomapper/pull/680

**Pull request closed without merging**
